// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TriageBot.Infrastructure.Persistence;

#nullable disable

namespace TriageBot.Infrastructure.Migrations
{
    [DbContext(typeof(TriageBotDbContext))]
    partial class TriageBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TriageBot.Core.Domain.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("AgentRuns");
                });

            modelBuilder.Entity("TriageBot.Core.Domain.AgentStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<int>("StepIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("AgentRunId", "StepIndex");

                    b.ToTable("AgentSteps");
                });

            modelBuilder.Entity("TriageBot.Core.Domain.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DraftReply")
                        .HasColumnType("text");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Urgency")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Body = "I keep getting 'invalid credentials' on the staff portal even though my password is correct.",
                            Category = "AccountAccess",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequesterEmail = "dewi@contoso.com",
                            Status = "New",
                            Subject = "Cannot login to portal",
                            Urgency = "High"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Body = "The corporate VPN drops every few minutes when I work from home, making it hard to stay connected.",
                            Category = "Network",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequesterEmail = "budi@contoso.com",
                            Status = "New",
                            Subject = "VPN keeps disconnecting",
                            Urgency = "Medium"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Body = "Please install Visual Studio 2022 Professional on my workstation for the new project.",
                            Category = "Software",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequesterEmail = "arif@contoso.com",
                            Status = "New",
                            Subject = "Request: install Visual Studio",
                            Urgency = "Low"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Body = "The shared printer near the 3rd floor kitchen shows as offline and nobody can print.",
                            Category = "Hardware",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequesterEmail = "siti@contoso.com",
                            Status = "New",
                            Subject = "Printer offline 3rd floor",
                            Urgency = "Medium"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            Body = "The order-management application is returning 500 errors for everyone. This is a full outage affecting production.",
                            Category = "Software",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequesterEmail = "ops@contoso.com",
                            Status = "New",
                            Subject = "URGENT: production app down for all users",
                            Urgency = "Critical"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            Body = "I forgot my Windows password and cannot sign in to my laptop. Please help me reset it.",
                            Category = "AccountAccess",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequesterEmail = "rina@contoso.com",
                            Status = "New",
                            Subject = "Forgot password",
                            Urgency = "Medium"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            Body = "My Outlook mailbox stopped syncing on my iPhone since yesterday; new messages only appear on the desktop.",
                            Category = "Email",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequesterEmail = "tono@contoso.com",
                            Status = "New",
                            Subject = "Email not syncing on phone",
                            Urgency = "Low"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            Body = "Onboarding a new analyst next week; please provision a standard laptop and accessories.",
                            Category = "Hardware",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequesterEmail = "hr@contoso.com",
                            Status = "New",
                            Subject = "New laptop request",
                            Urgency = "Low"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            Body = "Several files on the finance share were renamed with a strange extension and a ransom note appeared. Possible ransomware.",
                            Category = "Other",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequesterEmail = "finance@contoso.com",
                            Status = "New",
                            Subject = "Suspected data breach in finance share",
                            Urgency = "Critical"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            Body = "Wireless access points on the 2nd floor are unreachable; about 20 people have no connectivity.",
                            Category = "Network",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequesterEmail = "facilities@contoso.com",
                            Status = "New",
                            Subject = "Wi-Fi down across 2nd floor",
                            Urgency = "High"
                        });
                });

            modelBuilder.Entity("TriageBot.Core.Domain.AgentRun", b =>
                {
                    b.HasOne("TriageBot.Core.Domain.Ticket", "Ticket")
                        .WithMany("AgentRuns")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TriageBot.Core.Domain.AgentStep", b =>
                {
                    b.HasOne("TriageBot.Core.Domain.AgentRun", "AgentRun")
                        .WithMany("Steps")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRun");
                });

            modelBuilder.Entity("TriageBot.Core.Domain.AgentRun", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("TriageBot.Core.Domain.Ticket", b =>
                {
                    b.Navigation("AgentRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
